name: Generate Snake Game

on:
  schedule: # Run workflow every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Game from a gist
        uses: Platane/snk@master
        with:
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Create output directory
        run: mkdir -p dist

      - name: Generate Snake Game
        uses: Platane/snk/svg-only@v2
        with:
          output: dist/github-contribution-grid-snake.svg

      - name: Upload to GitHub Pages
        uses: actions/upload-artifact@v2
        with:
          name: snake-game
          path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
