name: Generate Snake Game

on:
  schedule: # Run workflow every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake game
        uses: Platane/snk/svg-only@v2
        with:
          output: dist/github-contribution-grid-snake.svg

      - name: Create output directory
        run: mkdir -p dist

      - name: Upload Snake Game to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: snake-game
          path: dist/github-contribution-grid-snake.svg

      - name: Update README with snake game
        run: |
          sed -i 's|!\[Snake animation\](.*)|!\[Snake animation\](https://raw.githubusercontent.com/${{ github.repository }}/main/.github/workflows/github-contribution-grid-snake.svg)|' README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update README with Snake game"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
